site_name: PySparkCLI Docs
site_description: This documentation contains the step-by-step procedure to create a PySpark project using a CLI. 
site_author: Jino Jossy
repo_url: https://github.com/qburst/PySparkCLI
repo_name: qburst/PySparkCLI
remote_branch: master
docs_dir: site_docs/
site_dir: docs/
theme: readthedocs
plugins:
  - search
  - mkdocs-versioning:
      version: 1.0.0
